import {
  Destination,
  TravelPackage,
  TravelSchedule,
  User,
  Coupon,
  Booking,
  Review,
  Notification,
  SupportTicket,
  AuditLog,
} from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    fullName: 'Raden Budi Santoso',
    email: 'admin@nusantaralive.com',
    phone: '+6281234567890',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    createdAt: '2026-01-10T08:00:00Z',
    isVerified: true,
  },
  {
    id: 'usr-staff-1',
    fullName: 'Siti Rahmawati',
    email: 'staff.siti@nusantaralive.com',
    phone: '+6281987654321',
    role: 'STAFF',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    createdAt: '2026-02-01T09:30:00Z',
    isVerified: true,
  },
  {
    id: 'usr-cust-1',
    fullName: 'Nabil Robbani',
    email: 'nabilrobbani6@gmail.com',
    phone: '+6285712345678',
    role: 'CUSTOMER',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    createdAt: '2026-03-05T14:15:00Z',
    isVerified: true,
  },
  {
    id: 'usr-cust-2',
    fullName: 'Clarissa Maharani',
    email: 'clarissa.m@example.com',
    phone: '+6281298761234',
    role: 'CUSTOMER',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    createdAt: '2026-03-12T10:00:00Z',
    isVerified: true,
  },
  {
    id: 'usr-cust-3',
    fullName: 'Michael Tanuwidjaja',
    email: 'michael.tan@example.com',
    phone: '+6287711223344',
    role: 'CUSTOMER',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    createdAt: '2026-04-02T16:20:00Z',
    isVerified: true,
  },
];

export const INITIAL_DESTINATIONS: Destination[] = [
  {
    id: 'dest-bali',
    name: 'Bali Island of the Gods',
    slug: 'bali-island',
    country: 'Indonesia',
    city: 'Denpasar & Ubud',
    description: 'Paradise island famous for volcanic mountains, iconic rice paddies, sandy beaches, ancient temples, and vibrant culture.',
    latitude: -8.409518,
    longitude: 115.188916,
    timezone: 'WITA (UTC+8)',
    category: 'BEACH',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=900&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&auto=format&fit=crop&q=80',
    ],
    featured: true,
    status: 'ACTIVE',
    rating: 4.9,
    packageCount: 4,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-labuan-bajo',
    name: 'Labuan Bajo & Komodo Island',
    slug: 'labuan-bajo-komodo',
    country: 'Indonesia',
    city: 'West Manggarai, Flores',
    description: 'Gateway to UNESCO Komodo National Park, featuring prehistoric dragons, surreal pink beaches, and breathtaking Padar Island viewpoint.',
    latitude: -8.453889,
    longitude: 119.887778,
    timezone: 'WITA (UTC+8)',
    category: 'ADVENTURE',
    imageUrl: 'https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?w=900&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=800&auto=format&fit=crop&q=80',
    ],
    featured: true,
    status: 'ACTIVE',
    rating: 4.95,
    packageCount: 3,
    createdAt: '2026-01-02T00:00:00Z',
  },
  {
    id: 'dest-raja-ampat',
    name: 'Raja Ampat Archipelago',
    slug: 'raja-ampat',
    country: 'Indonesia',
    city: 'Southwest Papua',
    description: 'The global epicenter of marine biodiversity with emerald cone-shaped karst islets, pristine crystal lagoons, and world-class diving.',
    latitude: -0.233333,
    longitude: 130.516667,
    timezone: 'WIT (UTC+9)',
    category: 'NATURE',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=900&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    ],
    featured: true,
    status: 'ACTIVE',
    rating: 5.0,
    packageCount: 2,
    createdAt: '2026-01-03T00:00:00Z',
  },
  {
    id: 'dest-yogyakarta',
    name: 'Yogyakarta Cultural Heritage',
    slug: 'yogyakarta-cultural',
    country: 'Indonesia',
    city: 'DI Yogyakarta',
    description: 'The soul of Javanese fine art, royal palaces, majestic 9th-century Borobudur & Prambanan temples, and vibrant street gastronomy.',
    latitude: -7.79558,
    longitude: 110.36949,
    timezone: 'WIB (UTC+7)',
    category: 'CULTURAL',
    imageUrl: 'https://images.unsplash.com/photo-1584810359583-96fc3448beaa?w=900&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1584810359583-96fc3448beaa?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1605649487212-47bdab064df8?w=800&auto=format&fit=crop&q=80',
    ],
    featured: false,
    status: 'ACTIVE',
    rating: 4.85,
    packageCount: 2,
    createdAt: '2026-01-04T00:00:00Z',
  },
  {
    id: 'dest-bromo',
    name: 'Mount Bromo & Semeru',
    slug: 'bromo-tengger-semeru',
    country: 'Indonesia',
    city: 'Probolinggo & Malang',
    description: 'Dramatic otherworldly caldera, sunrise at King Kong Hill, sea of volcanic whispering sand, and majestic active crater rim.',
    latitude: -7.942494,
    longitude: 112.953012,
    timezone: 'WIB (UTC+7)',
    category: 'MOUNTAIN',
    imageUrl: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=900&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&auto=format&fit=crop&q=80',
    ],
    featured: true,
    status: 'ACTIVE',
    rating: 4.9,
    packageCount: 2,
    createdAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'dest-lombok',
    name: 'Lombok & Gili Islands',
    slug: 'lombok-gili-islands',
    country: 'Indonesia',
    city: 'Mataram & North Lombok',
    description: 'Turquoise coastal paradise, car-free Gili coral reefs, Sasak traditional villages, and majestic Mount Rinjani hiking trails.',
    latitude: -8.650979,
    longitude: 116.324944,
    timezone: 'WITA (UTC+8)',
    category: 'BEACH',
    imageUrl: 'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?w=900&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?w=800&auto=format&fit=crop&q=80',
    ],
    featured: false,
    status: 'ACTIVE',
    rating: 4.88,
    packageCount: 2,
    createdAt: '2026-01-06T00:00:00Z',
  },
];

export const INITIAL_PACKAGES: TravelPackage[] = [
  {
    id: 'pkg-bali-luxury-4d3n',
    destinationId: 'dest-bali',
    destinationName: 'Bali Island of the Gods',
    title: 'Exotic Bali & Nusa Penida Luxury Escape',
    slug: 'exotic-bali-nusa-penida-luxury-4d3n',
    description: 'Experience the magic of Bali: sunrise yoga in Ubud, Kelingking T-Rex cliff exploration, private beach club at Uluwatu, and Jimbaran seafood sunset dinner.',
    duration: '4D3N',
    durationDays: 4,
    startLocation: 'Ngurah Rai International Airport (DPS)',
    endLocation: 'Ngurah Rai International Airport (DPS)',
    price: 4850000,
    discountPrice: 4250000,
    quota: 25,
    availableQuota: 18,
    minimumParticipant: 1,
    maximumParticipant: 25,
    status: 'ACTIVE',
    featured: true,
    category: 'BEACH',
    cancellationPolicy: 'Free cancellation up to 7 days before departure. 50% refund within 3-7 days. Non-refundable under 72 hours.',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=900&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&auto=format&fit=crop&q=80',
    ],
    itinerary: [
      {
        dayNumber: 1,
        title: 'Arrival & Ubud Cultural Heart',
        description: 'Airport VIP pickup, scenic drive to Ubud, check-in to jungle luxury villa, evening Kecak dance at Ubud Palace.',
        location: 'Ubud, Gianyar',
        startTime: '10:00',
        endTime: '20:30',
        meal: 'Dinner included',
        transport: 'Private Alphard / HiAce',
        accommodation: 'The Kayon Jungle Resort 5-Star',
      },
      {
        dayNumber: 2,
        title: 'Nusa Penida Island Expedition',
        description: 'Fast boat transfer to Nusa Penida. Visit Kelingking Beach cliff, Angel Billabong, Broken Beach, and snorkel at Crystal Bay.',
        location: 'Nusa Penida',
        startTime: '07:00',
        endTime: '17:30',
        meal: 'Breakfast, Seafood Lunch',
        transport: 'VIP Speedboat & Island 4WD',
        accommodation: 'The Kayon Jungle Resort 5-Star',
      },
      {
        dayNumber: 3,
        title: 'Uluwatu Sunset & Jimbaran Feast',
        description: 'Morning free leisure in Ubud. Afternoon visit to Uluwatu Temple perched 70m above crashing waves. Candlelight seafood dinner on Jimbaran Bay sands.',
        location: 'Uluwatu & Jimbaran',
        startTime: '13:00',
        endTime: '21:00',
        meal: 'Breakfast, BBQ Seafood Dinner',
        transport: 'Private Vehicle',
        accommodation: 'The Kayon Jungle Resort 5-Star',
      },
      {
        dayNumber: 4,
        title: 'Souvenir Heritage & Departure',
        description: 'Spa wellness massage treatment, shopping for premium artisan handicrafts at Krisna Heritage, transfer to airport.',
        location: 'Kuta & Airport',
        startTime: '09:00',
        endTime: '15:00',
        meal: 'Breakfast included',
        transport: 'Private Vehicle',
        accommodation: 'Check-out',
      },
    ],
    hotels: [
      {
        id: 'htl-kayon-ubud',
        name: 'The Kayon Jungle Resort Ubud',
        rating: 5,
        roomType: 'Valley Pool Villa Suite',
        location: 'Ubud, Bali',
        facilities: ['Private Infinity Pool', 'Spa & Wellness', 'High-Speed Wi-Fi', 'Breakfast Buffet', 'Jungle View'],
        imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&auto=format&fit=crop&q=80',
      },
    ],
    transports: [
      {
        id: 'trp-alphard',
        type: 'PRIVATE_CAR',
        provider: 'Nusantara VIP Luxury Chauffeur',
        vehicle: 'Toyota Alphard Executive Lounge',
        seatCapacity: 4,
      },
      {
        id: 'trp-speedboat',
        type: 'SPEEDBOAT',
        provider: 'Maruti Fast Cruise',
        vehicle: 'Twin-Engine High Speed Marine Catamaran',
        seatCapacity: 30,
      },
    ],
    inclusions: [
      '3 Nights luxury 5-star Villa accommodation with daily breakfast',
      'Private air-conditioned vehicle & dedicated tour guide',
      'VIP fast boat ticket to Nusa Penida round-trip',
      'All entrance tickets, donations, and parking fees',
      'Jimbaran beachfront candlelit seafood dinner',
      'Travel health & accident insurance up to Rp 100.000.000',
      'Complimentary chilled mineral water & cold towels',
    ],
    exclusions: [
      'Domestic or international flight tickets',
      'Personal laundry, minibar, and telephone expenses',
      'Tipping for guide and chauffeur (recommended)',
      'Single room supplement if solo traveler',
    ],
    rating: 4.92,
    reviewCount: 48,
    createdAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'pkg-labuan-bajo-phinisi-3d2n',
    destinationId: 'dest-labuan-bajo',
    destinationName: 'Labuan Bajo & Komodo Island',
    title: 'Liveaboard Phinisi Komodo Expedition 3D2N',
    slug: 'liveaboard-phinisi-komodo-expedition-3d2n',
    description: 'Sail through the prehistoric realm on a handcrafted wooden Phinisi yacht. Trek Padar Island at sunrise, snorkel with giant Manta Rays, and marvel at Komodo dragons.',
    duration: '3D2N',
    durationDays: 3,
    startLocation: 'Komodo Airport Labuan Bajo (LBJ)',
    endLocation: 'Komodo Airport Labuan Bajo (LBJ)',
    price: 6750000,
    discountPrice: 5900000,
    quota: 14,
    availableQuota: 8,
    minimumParticipant: 2,
    maximumParticipant: 14,
    status: 'ACTIVE',
    featured: true,
    category: 'ADVENTURE',
    cancellationPolicy: 'Cancellations 14+ days before departure eligible for 80% refund. Within 14 days 30% refund.',
    imageUrl: 'https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?w=900&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=800&auto=format&fit=crop&q=80',
    ],
    itinerary: [
      {
        dayNumber: 1,
        title: 'Boarding Phinisi & Kelor Island Trek',
        description: 'Pickup from airport, harbor transfer, board luxury wooden Phinisi. Sail to Kelor Island for hike, snorkeling at Manjarite, watch flying foxes at Kalong sunset.',
        location: 'Kelor & Kalong Island',
        startTime: '10:30',
        endTime: '20:00',
        meal: 'Lunch, Sunset Canapés, Dinner',
        transport: 'Luxury Phinisi Boat',
        accommodation: 'Phinisi Master Ocean Cabin',
      },
      {
        dayNumber: 2,
        title: 'Padar Sunrise, Pink Beach & Komodo Dragon Trek',
        description: 'Climb Padar Island 360-degree viewpoint at dawn. Relax on world-famous Pink Beach. Guided ranger trek on Komodo Island to witness ancient Komodo dragons.',
        location: 'Padar & Komodo Island',
        startTime: '05:00',
        endTime: '19:30',
        meal: 'Breakfast, Chef Lunch, BBQ Dinner under stars',
        transport: 'Luxury Phinisi Boat',
        accommodation: 'Phinisi Master Ocean Cabin',
      },
      {
        dayNumber: 3,
        title: 'Manta Point Snorkel & Return to Port',
        description: 'Swim alongside gentle giant Manta Rays at Manta Point reef. Visit pristine sandbar Taka Makassar, cruise back to Labuan Bajo harbor and airport drop-off.',
        location: 'Manta Point & Labuan Bajo',
        startTime: '07:30',
        endTime: '14:30',
        meal: 'Breakfast, Light Lunch',
        transport: 'Luxury Phinisi Boat & Port Transfer',
        accommodation: 'Check-out',
      },
    ],
    hotels: [
      {
        id: 'htl-phinisi-samudra',
        name: 'Samudra Raya Luxury Phinisi Yacht',
        rating: 5,
        roomType: 'Deluxe Ocean View Double Cabin',
        location: 'Komodo National Park waters',
        facilities: ['En-Suite Private Bathroom', 'Air Conditioning', 'Sundeck Jacuzzi', 'Chef Onboard', 'Paddleboard & Snorkel Gear'],
        imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
      },
    ],
    transports: [
      {
        id: 'trp-phinisi-vessel',
        type: 'SPEEDBOAT',
        provider: 'Nusantara Ocean Charters',
        vehicle: 'Grand Phinisi 38-meter Vessel',
        seatCapacity: 14,
      },
    ],
    inclusions: [
      '2 Nights stay onboard Deluxe Ocean Cabin with A/C and hot water',
      'All gourmet meals prepared fresh daily by private onboard Chef',
      'Complete snorkeling equipment & safety vests',
      'National Park ranger fee and English-speaking tour leader',
      'Underwater GoPro 4K photo & drone documentation',
      'Harbor transfers round-trip from Komodo Airport',
    ],
    exclusions: [
      'Komodo National Park entrance ticket (IDR 350.000 for WNI / IDR 550.000 for WNA)',
      'Crew tipping gratuity (recommended IDR 100.000/day)',
      'Alcoholic beverages',
    ],
    rating: 4.96,
    reviewCount: 39,
    createdAt: '2026-01-12T00:00:00Z',
  },
  {
    id: 'pkg-raja-ampat-ultimate-5d4n',
    destinationId: 'dest-raja-ampat',
    destinationName: 'Raja Ampat Archipelago',
    title: 'Raja Ampat Pianemo & Wayag Oceanic Wonderland 5D4N',
    slug: 'raja-ampat-pianemo-wayag-5d4n',
    description: 'The ultimate bucket-list expedition across Pianemo limestone peaks, Wayag lagoons, Telaga Bintang starfish bay, and diving with manta rays.',
    duration: '5D4N',
    durationDays: 5,
    startLocation: 'Dominik Edward Osok Airport Sorong (SOQ)',
    endLocation: 'Dominik Edward Osok Airport Sorong (SOQ)',
    price: 13500000,
    discountPrice: 11900000,
    quota: 12,
    availableQuota: 6,
    minimumParticipant: 2,
    maximumParticipant: 12,
    status: 'ACTIVE',
    featured: true,
    category: 'NATURE',
    cancellationPolicy: 'Cancellations 30 days prior eligible for 90% refund. Within 14-30 days 50% refund. Under 14 days non-refundable.',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=900&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    ],
    itinerary: [
      {
        dayNumber: 1,
        title: 'Arrival in Sorong & Ferry to Waisai',
        description: 'Airport arrival in Sorong, express ferry ticket to Waisai capital of Raja Ampat, check-in to overwater eco-resort.',
        location: 'Sorong to Waisai',
        startTime: '08:00',
        endTime: '17:00',
        meal: 'Lunch, Island Dinner',
        transport: 'Express Bahari VIP Ferry',
        accommodation: 'Raja Ampat Overwater Eco Resort',
      },
      {
        dayNumber: 2,
        title: 'Pianemo Icon & Star Lagoon',
        description: 'Climb 320 wooden steps to Pianemo viewpoint overlooking emerald karst islands. Swim in Telaga Bintang starfish shaped lagoon.',
        location: 'Pianemo, Gam Island',
        startTime: '08:00',
        endTime: '18:00',
        meal: 'Breakfast, Picnic Lunch, Fresh Fish Dinner',
        transport: 'Private 3-Engine Marine Speedboat',
        accommodation: 'Raja Ampat Overwater Eco Resort',
      },
      {
        dayNumber: 3,
        title: 'Wayag Karst Pinnacles (Weather Permitting) or Kabui Bay',
        description: 'Witness the crown jewel of Raja Ampat: Wayag pinnacle climbing, shark nursery beach encounter, and pristine coral drift snorkeling.',
        location: 'Wayag Archipelago',
        startTime: '06:00',
        endTime: '19:00',
        meal: 'Breakfast, Lunch, Dinner',
        transport: 'Speedboat',
        accommodation: 'Raja Ampat Overwater Eco Resort',
      },
      {
        dayNumber: 4,
        title: 'Red Bird of Paradise & Village Encounter',
        description: 'Early morning forest trek to observe rare Cenderawasih (Bird of Paradise) mating ritual. Visit Sawinggrai village and Yenbuba jetty coral garden.',
        location: 'Sawinggrai & Yenbuba',
        startTime: '05:30',
        endTime: '18:00',
        meal: 'Breakfast, Lunch, Farewell BBQ',
        transport: 'Speedboat',
        accommodation: 'Raja Ampat Overwater Eco Resort',
      },
      {
        dayNumber: 5,
        title: 'Waisai to Sorong & Departure',
        description: 'Morning breakfast on overwater terrace, ferry back to Sorong mainland, souvenir shop for Papuan noken, airport drop-off.',
        location: 'Sorong',
        startTime: '07:30',
        endTime: '14:00',
        meal: 'Breakfast included',
        transport: 'VIP Ferry & Airport Van',
        accommodation: 'Check-out',
      },
    ],
    hotels: [
      {
        id: 'htl-raja-eco',
        name: 'Raja Ampat Overwater Eco Lodge',
        rating: 5,
        roomType: 'Overwater Bungalow',
        location: 'Kri Island, Raja Ampat',
        facilities: ['Direct Coral Reef Access', 'Solar Energy', 'Mosquito Netting', 'Full Board Cuisine', 'Snorkeling Gear'],
        imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80',
      },
    ],
    transports: [
      {
        id: 'trp-sorong-ferry',
        type: 'SPEEDBOAT',
        provider: 'Express Bahari VIP',
        vehicle: 'Commercial High Speed Ferry',
        seatCapacity: 120,
      },
    ],
    inclusions: [
      '4 Nights accommodation in Overwater Bungalow',
      'All meals (Breakfast, Lunch, Dinner, afternoon tea/coffee & snacks)',
      'Private speedboat charter with twin 200HP Yamaha engines & captain',
      'Raja Ampat Marine Environmental PIN (Tarif Layanan Pemeliharaan Lingkungan)',
      'Full snorkeling equipment + lifejackets',
      'Local Papuan certified nature guides & bird-watching rangers',
    ],
    exclusions: [
      'Domestic flights to Sorong (SOQ)',
      'Diving gear rental (optional add-on IDR 750.000/dive)',
      'Personal alcohol and tipping',
    ],
    rating: 5.0,
    reviewCount: 26,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'pkg-bromo-malang-3d2n',
    destinationId: 'dest-bromo',
    destinationName: 'Mount Bromo & Semeru',
    title: 'Bromo Midnight Sunrise 4WD & Malang Heritage 3D2N',
    slug: 'bromo-midnight-sunrise-malang-3d2n',
    description: 'Iconic sunrise over Mount Bromo active crater, 4WD Hardtop jeep across the Sea of Sand, Whispering Sand, Teletubbies savanna hill, and apple picking in Batu Malang.',
    duration: '3D2N',
    durationDays: 3,
    startLocation: 'Juanda Airport Surabaya (SUB) or Malang (MLG)',
    endLocation: 'Juanda Airport Surabaya (SUB)',
    price: 2450000,
    discountPrice: 2150000,
    quota: 30,
    availableQuota: 22,
    minimumParticipant: 2,
    maximumParticipant: 30,
    status: 'ACTIVE',
    featured: true,
    category: 'MOUNTAIN',
    cancellationPolicy: 'Free cancellation up to 5 days before trip date. 50% within 2-5 days.',
    imageUrl: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=900&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800&auto=format&fit=crop&q=80',
    ],
    itinerary: [
      {
        dayNumber: 1,
        title: 'Surabaya Pickup & Scenic Batu Malang Tour',
        description: 'Pickup from airport or train station, drive to mountain town of Batu. Visit Kusuma Agrowisata organic apple orchard, check-in to mountain resort.',
        location: 'Batu, Malang',
        startTime: '11:00',
        endTime: '19:00',
        meal: 'Lunch, Dinner',
        transport: 'Air-conditioned Van',
        accommodation: 'Golden Tulip Holland Resort Batu 5-Star',
      },
      {
        dayNumber: 2,
        title: 'Bromo Midnight Sunrise Jeep Safari',
        description: '00:30 AM departure to Sukapura. Switch to 4WD Toyota Land Cruiser Jeep. Sunrise over King Kong Hill, crater climb, Pasir Berbisik sand sea, and savanna.',
        location: 'Bromo Tengger Semeru National Park',
        startTime: '00:30',
        endTime: '14:00',
        meal: 'Midnight snack, Mountain Breakfast, Lunch',
        transport: '4WD Toyota Hardtop 4x4',
        accommodation: 'Golden Tulip Holland Resort Batu 5-Star',
      },
      {
        dayNumber: 3,
        title: 'Coban Rondo Waterfall & Departure',
        description: 'Breakfast, visit Coban Rondo majestic waterfall & labyrinth garden, souvenir shopping for famous Malang bakso & strudel, airport return.',
        location: 'Pujon & Surabaya',
        startTime: '08:30',
        endTime: '15:30',
        meal: 'Breakfast, Malang Bakso Lunch',
        transport: 'Air-conditioned Van',
        accommodation: 'Check-out',
      },
    ],
    hotels: [
      {
        id: 'htl-golden-tulip-batu',
        name: 'Golden Tulip Holland Resort Batu',
        rating: 5,
        roomType: 'Premier Mountain Balcony Room',
        location: 'Batu, East Java',
        facilities: ['Heated Pool', 'Balcony with Mountain View', 'Buffet Breakfast', 'Spa', 'Fitness Center'],
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
      },
    ],
    transports: [
      {
        id: 'trp-jeep-bromo',
        type: 'PRIVATE_CAR',
        provider: 'Tengger Hardtop Jeep Community',
        vehicle: 'Toyota Land Cruiser 4x4 FJ40',
        seatCapacity: 6,
      },
    ],
    inclusions: [
      '2 Nights stay in 5-star Golden Tulip Resort with daily buffet breakfast',
      'Private 4WD Toyota Hardtop Jeep for Bromo sunrise tour',
      'All entrance tickets to Bromo National Park & Batu destinations',
      'Professional guide & photo assistance',
      'Complimentary apple picking tasting at farm',
    ],
    exclusions: ['Horse ride fee across Bromo sand sea (optional IDR 150.000)', 'Personal expenses'],
    rating: 4.89,
    reviewCount: 54,
    createdAt: '2026-01-18T00:00:00Z',
  },
  {
    id: 'pkg-jogja-royal-3d2n',
    destinationId: 'dest-yogyakarta',
    destinationName: 'Yogyakarta Cultural Heritage',
    title: 'Royal Yogyakarta Heritage & Borobudur Sunrise 3D2N',
    slug: 'royal-yogyakarta-heritage-borobudur-3d2n',
    description: 'Immerse yourself in centuries of Javanese elegance: UNESCO Borobudur temple morning light, Prambanan Ramayana ballet, Kraton Palace, and Merapi Jeep adventure.',
    duration: '3D2N',
    durationDays: 3,
    startLocation: 'Yogyakarta International Airport (YIA)',
    endLocation: 'Yogyakarta International Airport (YIA)',
    price: 3200000,
    discountPrice: 2850000,
    quota: 20,
    availableQuota: 15,
    minimumParticipant: 2,
    maximumParticipant: 20,
    status: 'ACTIVE',
    featured: false,
    category: 'CULTURAL',
    cancellationPolicy: 'Free cancellation up to 7 days before trip.',
    imageUrl: 'https://images.unsplash.com/photo-1584810359583-96fc3448beaa?w=900&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1584810359583-96fc3448beaa?w=800&auto=format&fit=crop&q=80',
    ],
    itinerary: [
      {
        dayNumber: 1,
        title: 'Kraton Royal Palace & Tamansari Water Castle',
        description: 'Airport welcome, check-in to historic heritage hotel, explore Sultan Palace & Underground Mosque at Tamansari, sunset dinner at Bukit Bintang.',
        location: 'Kota Yogyakarta',
        startTime: '10:00',
        endTime: '20:30',
        meal: 'Lunch, Gudeg Royal Dinner',
        transport: 'Air-conditioned Van',
        accommodation: 'The Phoenix Hotel Yogyakarta (MGallery)',
      },
      {
        dayNumber: 2,
        title: 'Borobudur Majestic Monolith & Merapi Lava Tour',
        description: 'Early morning VIP entrance to Borobudur Temple structure. Afternoon exhilarating 4x4 Jeep safari through Merapi volcanic eruption historical path.',
        location: 'Magelang & Kaliurang',
        startTime: '06:00',
        endTime: '18:00',
        meal: 'Breakfast, Traditional Javanese Lunch, Dinner',
        transport: 'Private Van & 4x4 Jeep',
        accommodation: 'The Phoenix Hotel Yogyakarta (MGallery)',
      },
      {
        dayNumber: 3,
        title: 'Prambanan Temple, Silverworks & Malioboro Walk',
        description: 'Visit towering 9th-century Prambanan Hindu temple complex, Kotagede silver artisan workshop, Malioboro stroll, airport transfer.',
        location: 'Sleman & YIA Airport',
        startTime: '08:30',
        endTime: '16:00',
        meal: 'Breakfast, Lunch',
        transport: 'Private Van',
        accommodation: 'Check-out',
      },
    ],
    hotels: [
      {
        id: 'htl-phoenix-jogja',
        name: 'The Phoenix Hotel Yogyakarta - MGallery',
        rating: 5,
        roomType: 'Heritage Deluxe Suite',
        location: 'Jl. Jenderal Sudirman, Yogyakarta',
        facilities: ['Colonial Architecture', 'Courtyard Pool', 'Fine Dining Restaurant', 'Spa'],
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
      },
    ],
    transports: [
      {
        id: 'trp-hiace-jogja',
        type: 'BUS',
        provider: 'Nusantara Royal Coach',
        vehicle: 'Toyota HiAce Premio Luxury 10-seater',
        seatCapacity: 10,
      },
    ],
    inclusions: [
      '2 Nights stay in 5-star Heritage MGallery Hotel with daily breakfast',
      'VIP Borobudur monument climb permit',
      'Merapi Lava Tour 4WD Jeep rental with driver',
      'All culinary experiences including iconic Gudeg Yu Djum & royal feast',
    ],
    exclusions: ['Flight tickets to YIA', 'Personal expenses'],
    rating: 4.88,
    reviewCount: 31,
    createdAt: '2026-01-20T00:00:00Z',
  },
];

export const INITIAL_SCHEDULES: TravelSchedule[] = [
  // Schedules for Bali
  {
    id: 'sch-bali-1',
    packageId: 'pkg-bali-luxury-4d3n',
    departureDate: '2026-10-15',
    returnDate: '2026-10-18',
    quota: 25,
    remainingQuota: 18,
    status: 'AVAILABLE',
    seasonalSurgeMultiplier: 1.0,
  },
  {
    id: 'sch-bali-2',
    packageId: 'pkg-bali-luxury-4d3n',
    departureDate: '2026-10-24',
    returnDate: '2026-10-27',
    quota: 25,
    remainingQuota: 4,
    status: 'ALMOST_FULL',
    seasonalSurgeMultiplier: 1.05,
  },
  {
    id: 'sch-bali-3',
    packageId: 'pkg-bali-luxury-4d3n',
    departureDate: '2026-11-05',
    returnDate: '2026-11-08',
    quota: 25,
    remainingQuota: 25,
    status: 'AVAILABLE',
    seasonalSurgeMultiplier: 1.0,
  },
  {
    id: 'sch-bali-4',
    packageId: 'pkg-bali-luxury-4d3n',
    departureDate: '2026-11-18',
    returnDate: '2026-11-21',
    quota: 25,
    remainingQuota: 0,
    status: 'FULL',
    seasonalSurgeMultiplier: 1.15,
  },

  // Schedules for Labuan Bajo
  {
    id: 'sch-bajo-1',
    packageId: 'pkg-labuan-bajo-phinisi-3d2n',
    departureDate: '2026-10-10',
    returnDate: '2026-10-12',
    quota: 14,
    remainingQuota: 8,
    status: 'AVAILABLE',
    seasonalSurgeMultiplier: 1.0,
  },
  {
    id: 'sch-bajo-2',
    packageId: 'pkg-labuan-bajo-phinisi-3d2n',
    departureDate: '2026-10-20',
    returnDate: '2026-10-22',
    quota: 14,
    remainingQuota: 2,
    status: 'ALMOST_FULL',
    seasonalSurgeMultiplier: 1.0,
  },
  {
    id: 'sch-bajo-3',
    packageId: 'pkg-labuan-bajo-phinisi-3d2n',
    departureDate: '2026-11-07',
    returnDate: '2026-11-09',
    quota: 14,
    remainingQuota: 14,
    status: 'AVAILABLE',
    seasonalSurgeMultiplier: 1.0,
  },

  // Schedules for Raja Ampat
  {
    id: 'sch-raja-1',
    packageId: 'pkg-raja-ampat-ultimate-5d4n',
    departureDate: '2026-10-22',
    returnDate: '2026-10-26',
    quota: 12,
    remainingQuota: 6,
    status: 'AVAILABLE',
    seasonalSurgeMultiplier: 1.0,
  },
  {
    id: 'sch-raja-2',
    packageId: 'pkg-raja-ampat-ultimate-5d4n',
    departureDate: '2026-11-12',
    returnDate: '2026-11-16',
    quota: 12,
    remainingQuota: 12,
    status: 'AVAILABLE',
    seasonalSurgeMultiplier: 1.0,
  },

  // Schedules for Bromo
  {
    id: 'sch-bromo-1',
    packageId: 'pkg-bromo-malang-3d2n',
    departureDate: '2026-10-12',
    returnDate: '2026-10-14',
    quota: 30,
    remainingQuota: 22,
    status: 'AVAILABLE',
    seasonalSurgeMultiplier: 1.0,
  },
  {
    id: 'sch-bromo-2',
    packageId: 'pkg-bromo-malang-3d2n',
    departureDate: '2026-10-26',
    returnDate: '2026-10-28',
    quota: 30,
    remainingQuota: 5,
    status: 'ALMOST_FULL',
    seasonalSurgeMultiplier: 1.0,
  },

  // Schedules for Jogja
  {
    id: 'sch-jogja-1',
    packageId: 'pkg-jogja-royal-3d2n',
    departureDate: '2026-10-16',
    returnDate: '2026-10-18',
    quota: 20,
    remainingQuota: 15,
    status: 'AVAILABLE',
    seasonalSurgeMultiplier: 1.0,
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'cpn-explore-indo',
    code: 'EXPLOREINDONESIA',
    name: 'Wonderful Indonesia Special',
    description: '15% discount for all domestic vacation packages across archipelago',
    type: 'PERCENTAGE',
    value: 15,
    minimumTransaction: 3000000,
    maximumDiscount: 1500000,
    usageLimit: 200,
    usageCount: 42,
    userLimit: 1,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    status: 'ACTIVE',
  },
  {
    id: 'cpn-bali-beach',
    code: 'BALIBEACH20',
    name: 'Bali Gateway Promo',
    description: 'Flat Rp 500.000 off on Bali luxury escape bookings',
    type: 'FIXED',
    value: 500000,
    minimumTransaction: 4000000,
    usageLimit: 100,
    usageCount: 19,
    userLimit: 1,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    status: 'ACTIVE',
  },
  {
    id: 'cpn-komodo-adventure',
    code: 'KOMODO750',
    name: 'Komodo Liveaboard Bonus',
    description: 'Rp 750.000 discount for Labuan Bajo Phinisi adventures',
    type: 'FIXED',
    value: 750000,
    minimumTransaction: 5000000,
    usageLimit: 50,
    usageCount: 12,
    userLimit: 1,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    status: 'ACTIVE',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-2026-001',
    bookingCode: 'TRV-2026-000001',
    userId: 'usr-cust-1',
    customerName: 'Nabil Robbani',
    customerEmail: 'nabilrobbani6@gmail.com',
    customerPhone: '+6285712345678',
    packageId: 'pkg-bali-luxury-4d3n',
    packageTitle: 'Exotic Bali & Nusa Penida Luxury Escape',
    destinationName: 'Bali Island of the Gods',
    scheduleId: 'sch-bali-1',
    departureDate: '2026-10-15',
    returnDate: '2026-10-18',
    totalTravelers: 2,
    travelers: [
      {
        id: 'trv-1',
        fullName: 'Nabil Robbani',
        type: 'ADULT',
        gender: 'MALE',
        dateOfBirth: '1998-05-14',
        nationality: 'Indonesian',
        identityNumber: '3171011405980001',
        phone: '+6285712345678',
        email: 'nabilrobbani6@gmail.com',
        specialRequest: 'Jungle view villa room, high floor',
      },
      {
        id: 'trv-2',
        fullName: 'Sarah Robbani',
        type: 'ADULT',
        gender: 'FEMALE',
        dateOfBirth: '2000-08-22',
        nationality: 'Indonesian',
        identityNumber: '3171012208000002',
        phone: '+6285712345679',
        specialRequest: 'Vegetarian seafood option',
      },
    ],
    unitPrice: 4250000,
    subtotal: 8500000,
    discount: 1275000,
    couponCode: 'EXPLOREINDONESIA',
    tax: 794750,
    serviceFee: 50000,
    totalAmount: 8069750,
    bookingStatus: 'CONFIRMED',
    paymentStatus: 'PAID',
    paymentMethod: 'BCA_VA',
    paymentExpiresAt: '2026-09-20T10:15:00Z',
    paidAt: '2026-09-20T10:04:12Z',
    confirmedAt: '2026-09-20T10:04:15Z',
    invoiceNumber: 'INV-2026-000001',
    createdAt: '2026-09-20T09:55:00Z',
    updatedAt: '2026-09-20T10:04:15Z',
  },
  {
    id: 'bk-2026-002',
    bookingCode: 'TRV-2026-000002',
    userId: 'usr-cust-2',
    customerName: 'Clarissa Maharani',
    customerEmail: 'clarissa.m@example.com',
    customerPhone: '+6281298761234',
    packageId: 'pkg-labuan-bajo-phinisi-3d2n',
    packageTitle: 'Liveaboard Phinisi Komodo Expedition 3D2N',
    destinationName: 'Labuan Bajo & Komodo Island',
    scheduleId: 'sch-bajo-1',
    departureDate: '2026-10-10',
    returnDate: '2026-10-12',
    totalTravelers: 2,
    travelers: [
      {
        id: 'trv-3',
        fullName: 'Clarissa Maharani',
        type: 'ADULT',
        gender: 'FEMALE',
        dateOfBirth: '1995-11-03',
        nationality: 'Indonesian',
        identityNumber: '3201010311950003',
        phone: '+6281298761234',
        email: 'clarissa.m@example.com',
      },
      {
        id: 'trv-4',
        fullName: 'Andika Pratama',
        type: 'ADULT',
        gender: 'MALE',
        dateOfBirth: '1994-02-18',
        nationality: 'Indonesian',
        identityNumber: '3201011802940004',
      },
    ],
    unitPrice: 5900000,
    subtotal: 11800000,
    discount: 750000,
    couponCode: 'KOMODO750',
    tax: 1215500,
    serviceFee: 50000,
    totalAmount: 12315500,
    bookingStatus: 'WAITING_PAYMENT',
    paymentStatus: 'PENDING',
    paymentMethod: 'MANDIRI_VA',
    paymentExpiresAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'bk-2026-003',
    bookingCode: 'TRV-2026-000003',
    userId: 'usr-cust-3',
    customerName: 'Michael Tanuwidjaja',
    customerEmail: 'michael.tan@example.com',
    customerPhone: '+6287711223344',
    packageId: 'pkg-raja-ampat-ultimate-5d4n',
    packageTitle: 'Raja Ampat Pianemo & Wayag Oceanic Wonderland 5D4N',
    destinationName: 'Raja Ampat Archipelago',
    scheduleId: 'sch-raja-1',
    departureDate: '2026-10-22',
    returnDate: '2026-10-26',
    totalTravelers: 1,
    travelers: [
      {
        id: 'trv-5',
        fullName: 'Michael Tanuwidjaja',
        type: 'ADULT',
        gender: 'MALE',
        dateOfBirth: '1991-07-29',
        nationality: 'Indonesian',
        identityNumber: '3174022907910005',
        phone: '+6287711223344',
        email: 'michael.tan@example.com',
        specialRequest: 'Diving master certification equipment rental',
      },
    ],
    unitPrice: 11900000,
    subtotal: 11900000,
    discount: 1500000,
    couponCode: 'EXPLOREINDONESIA',
    tax: 1144000,
    serviceFee: 50000,
    totalAmount: 11594000,
    bookingStatus: 'PAID',
    paymentStatus: 'PAID',
    paymentMethod: 'QRIS',
    paymentExpiresAt: '2026-09-18T14:30:00Z',
    paidAt: '2026-09-18T14:15:30Z',
    confirmedAt: '2026-09-18T14:16:00Z',
    invoiceNumber: 'INV-2026-000003',
    createdAt: '2026-09-18T14:05:00Z',
    updatedAt: '2026-09-18T14:16:00Z',
  },
  {
    id: 'bk-2026-004',
    bookingCode: 'TRV-2026-000004',
    userId: 'usr-cust-2',
    customerName: 'Clarissa Maharani',
    customerEmail: 'clarissa.m@example.com',
    customerPhone: '+6281298761234',
    packageId: 'pkg-bromo-malang-3d2n',
    packageTitle: 'Bromo Midnight Sunrise 4WD & Malang Heritage 3D2N',
    destinationName: 'Mount Bromo & Semeru',
    scheduleId: 'sch-bromo-1',
    departureDate: '2026-08-10',
    returnDate: '2026-08-12',
    totalTravelers: 2,
    travelers: [
      {
        id: 'trv-6',
        fullName: 'Clarissa Maharani',
        type: 'ADULT',
        gender: 'FEMALE',
        dateOfBirth: '1995-11-03',
        nationality: 'Indonesian',
        identityNumber: '3201010311950003',
      },
      {
        id: 'trv-7',
        fullName: 'Dian Permata',
        type: 'ADULT',
        gender: 'FEMALE',
        dateOfBirth: '1996-04-12',
        nationality: 'Indonesian',
        identityNumber: '3201011204960007',
      },
    ],
    unitPrice: 2150000,
    subtotal: 4300000,
    discount: 0,
    tax: 473000,
    serviceFee: 50000,
    totalAmount: 4823000,
    bookingStatus: 'COMPLETED',
    paymentStatus: 'PAID',
    paymentMethod: 'BCA_VA',
    paymentExpiresAt: '2026-08-01T12:00:00Z',
    paidAt: '2026-08-01T11:45:00Z',
    confirmedAt: '2026-08-01T11:46:00Z',
    completedAt: '2026-08-12T18:00:00Z',
    invoiceNumber: 'INV-2026-000004',
    createdAt: '2026-08-01T11:30:00Z',
    updatedAt: '2026-08-12T18:00:00Z',
  },
  {
    id: 'bk-2026-005',
    bookingCode: 'TRV-2026-000005',
    userId: 'usr-cust-3',
    customerName: 'Michael Tanuwidjaja',
    customerEmail: 'michael.tan@example.com',
    customerPhone: '+6287711223344',
    packageId: 'pkg-jogja-royal-3d2n',
    packageTitle: 'Royal Yogyakarta Heritage & Borobudur Sunrise 3D2N',
    destinationName: 'Yogyakarta Cultural Heritage',
    scheduleId: 'sch-jogja-1',
    departureDate: '2026-09-01',
    returnDate: '2026-09-03',
    totalTravelers: 1,
    travelers: [
      {
        id: 'trv-8',
        fullName: 'Michael Tanuwidjaja',
        type: 'ADULT',
        gender: 'MALE',
        dateOfBirth: '1991-07-29',
        nationality: 'Indonesian',
        identityNumber: '3174022907910005',
      },
    ],
    unitPrice: 2850000,
    subtotal: 2850000,
    discount: 0,
    tax: 313500,
    serviceFee: 50000,
    totalAmount: 3213500,
    bookingStatus: 'REFUND_REQUESTED',
    paymentStatus: 'PAID',
    paymentMethod: 'CREDIT_CARD',
    paymentExpiresAt: '2026-08-20T10:00:00Z',
    paidAt: '2026-08-20T09:40:00Z',
    refundAmount: 2850000 * 0.8, // 80% refund policy
    refundStatus: 'REQUESTED',
    cancelReason: 'Medical emergency - physician medical certificate provided.',
    createdAt: '2026-08-20T09:30:00Z',
    updatedAt: '2026-08-25T14:10:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    bookingId: 'bk-2026-004',
    packageId: 'pkg-bromo-malang-3d2n',
    packageTitle: 'Bromo Midnight Sunrise 4WD & Malang Heritage 3D2N',
    userId: 'usr-cust-2',
    userName: 'Clarissa Maharani',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Pengalaman sunrise Bromo luar biasa! Driver jeep Pak Joko sangat mahir dan fotografer handal. Hotel Golden Tulip Batu sangat nyaman dan sarapan melimpah.',
    status: 'APPROVED',
    createdAt: '2026-08-13T09:12:00Z',
  },
  {
    id: 'rev-2',
    bookingId: 'bk-2026-001',
    packageId: 'pkg-bali-luxury-4d3n',
    packageTitle: 'Exotic Bali & Nusa Penida Luxury Escape',
    userId: 'usr-cust-1',
    userName: 'Nabil Robbani',
    userAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Pelayanan kelas satu! Villa di Kayon Ubud suasananya magis, fastboat ke Nusa Penida nyaman dan tepat waktu. Pemandu ramah sekali.',
    status: 'APPROVED',
    createdAt: '2026-09-20T12:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'usr-cust-1',
    title: 'Booking Confirmed!',
    message: 'Your booking TRV-2026-000001 for Exotic Bali & Nusa Penida is confirmed. Invoice is ready for download.',
    type: 'BOOKING',
    isRead: false,
    createdAt: '2026-09-20T10:05:00Z',
  },
  {
    id: 'notif-2',
    userId: 'usr-cust-2',
    title: 'Payment Reminder',
    message: 'Booking TRV-2026-000002 has 15 minutes remaining to complete Mandiri Virtual Account payment.',
    type: 'PAYMENT',
    isRead: false,
    createdAt: '2026-09-21T08:00:00Z',
  },
  {
    id: 'notif-3',
    title: 'System Notice: Quota Concurrency Guard',
    message: 'Distributed Redis lock active. Quota atomic reservation verified with 0 oversell anomalies.',
    type: 'SYSTEM',
    isRead: true,
    createdAt: '2026-09-21T09:00:00Z',
  },
  {
    id: 'notif-4',
    title: 'Promo Alert: EXPLOREINDONESIA',
    message: 'Enjoy 15% discount on all domestic packages until end of 2026 with code EXPLOREINDONESIA.',
    type: 'PROMO',
    isRead: true,
    createdAt: '2026-09-21T07:30:00Z',
  },
];

export const INITIAL_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'tkt-001',
    ticketCode: 'TKT-2026-001',
    userId: 'usr-cust-3',
    userName: 'Michael Tanuwidjaja',
    userEmail: 'michael.tan@example.com',
    subject: 'Refund request review for Booking TRV-2026-000005',
    status: 'OPEN',
    priority: 'HIGH',
    category: 'REFUND',
    messages: [
      {
        id: 'msg-1',
        ticketId: 'tkt-001',
        senderId: 'usr-cust-3',
        senderName: 'Michael Tanuwidjaja',
        senderRole: 'CUSTOMER',
        message: 'Halo tim support, saya telah melampirkan surat keterangan dokter karena demam berdarah sehingga tidak bisa mengikuti trip Yogyakarta. Mohon bantu proses refund sesuai kebijakan.',
        createdAt: '2026-08-25T14:15:00Z',
      },
      {
        id: 'msg-2',
        ticketId: 'tkt-001',
        senderId: 'usr-staff-1',
        senderName: 'Siti Rahmawati',
        senderRole: 'STAFF',
        message: 'Halo Pak Michael, kami turut bersimpati atas kondisi kesehatan Bapak. Dokumen telah kami terima dan sedang diverifikasi oleh tim keuangan untuk pengembalian 80% sesuai klausul 7 hari sebelum keberangkatan.',
        createdAt: '2026-08-25T15:00:00Z',
      },
    ],
    createdAt: '2026-08-25T14:15:00Z',
    updatedAt: '2026-08-25T15:00:00Z',
  },
  {
    id: 'tkt-002',
    ticketCode: 'TKT-2026-002',
    userId: 'usr-cust-1',
    userName: 'Nabil Robbani',
    userEmail: 'nabilrobbani6@gmail.com',
    subject: 'Dietary restriction update for Nusa Penida trip',
    status: 'RESOLVED',
    priority: 'LOW',
    category: 'BOOKING',
    messages: [
      {
        id: 'msg-3',
        ticketId: 'tkt-002',
        senderId: 'usr-cust-1',
        senderName: 'Nabil Robbani',
        senderRole: 'CUSTOMER',
        message: 'Halo, untuk traveler Sarah Robbani mohon dicatat alergi kacang dan seafood udang. Mohon menu ayam/ikan fillet saja saat di Jimbaran.',
        createdAt: '2026-09-20T11:00:00Z',
      },
      {
        id: 'msg-4',
        ticketId: 'tkt-002',
        senderId: 'usr-staff-1',
        senderName: 'Siti Rahmawati',
        senderRole: 'STAFF',
        message: 'Sudah kami konfirmasi dan teruskan kepada chef restoran Jimbaran dan restoran villa. Tim kuliner akan menyiapkan menu khusus bebas alergen.',
        createdAt: '2026-09-20T11:45:00Z',
      },
    ],
    createdAt: '2026-09-20T11:00:00Z',
    updatedAt: '2026-09-20T11:45:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    userId: 'usr-admin-1',
    userName: 'Raden Budi Santoso',
    userRole: 'ADMIN',
    action: 'CREATE_TRAVEL_PACKAGE',
    entity: 'TravelPackage',
    entityId: 'pkg-raja-ampat-ultimate-5d4n',
    newValue: 'Created package: Raja Ampat Pianemo & Wayag 5D4N with 12 quota',
    ipAddress: '103.28.14.92',
    timestamp: '2026-01-15T00:05:00Z',
  },
  {
    id: 'aud-002',
    userId: 'usr-cust-1',
    userName: 'Nabil Robbani',
    userRole: 'CUSTOMER',
    action: 'CREATE_BOOKING',
    entity: 'Booking',
    entityId: 'bk-2026-001',
    newValue: 'Booking TRV-2026-000001 created for 2 travelers, quota reserved: 2',
    ipAddress: '180.252.164.12',
    timestamp: '2026-09-20T09:55:00Z',
  },
  {
    id: 'aud-003',
    userId: 'usr-staff-1',
    userName: 'Siti Rahmawati',
    userRole: 'STAFF',
    action: 'VERIFY_PAYMENT',
    entity: 'Payment',
    entityId: 'bk-2026-001',
    oldValue: 'WAITING_PAYMENT',
    newValue: 'PAID & CONFIRMED via BCA Virtual Account',
    ipAddress: '103.28.14.95',
    timestamp: '2026-09-20T10:04:15Z',
  },
  {
    id: 'aud-004',
    userId: 'usr-admin-1',
    userName: 'Raden Budi Santoso',
    userRole: 'ADMIN',
    action: 'PUBLISH_PROMO',
    entity: 'Coupon',
    entityId: 'cpn-explore-indo',
    newValue: 'Activated Coupon EXPLOREINDONESIA with 15% discount and 200 quota',
    ipAddress: '103.28.14.92',
    timestamp: '2026-09-21T06:00:00Z',
  },
];
